### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by FerDR89** [ayrton08/dwf-m8-desafio-#1]
Buenas Ayrton, como estas?
Felicitaciones por llegar haata aca!
Estuve probando recien la app desde el cel y no estoy pudiendo ver las mascotas que reporte.
Hace todo el flujo, me dice que la reporte pero cuando voy a my reports pets no me figuran. Me deslogie y tampoco encontré mascotas cercas.
Además de eso, cuando quiero reportar una mascota en X lugar siempre me vuelve a llevar a mi ubicación sea que aprite el botón mi ubicación o que lo escriba desde el cel y apriete "ir"

**Comment by amunozdev** [comment]
Buenas Ayrton como va?
Sumando a lo de Fer, en la page "My Reports" aparecen reportes de mascotas que yo no hice, es decir, de otra cuenta:
![Captura desde 2022-07-17 20-52-38](https://user-images.githubusercontent.com/77214476/179429882-2bf43043-81d5-4140-832a-fa53df20eb92.png)

**Comment by ayrton08** [comment]
Buenas! Bueno primero que nada gracias @FerDR89 y @alexismunoz1 por chequear mi desafio, ahi le estuve haciendo algunas correciones en base a las sugerencias que me hicieron y creo que quedo, les pido si lo pueden chequear nuevamente please, lo unico que haciendo referencia a lo que dijo Fer sobre la ubicacion, en el form para reportar una pet el input "Location Name" funciona solo como un nombre de referencia hacia el lugar y no como un buscador de lugares.. para reportar la ubicacion si o si hay que marcarlo en el map.. bueno aguardo el feedback, Saludos compañeros! 😁👌

**Comment by FerDR89** [comment]
Buenas, Como va?
Estuve testeando la app y en home se rompe:

![image](https://user-images.githubusercontent.com/74626765/180107957-62a124a4-bf76-4b1d-89ff-00a9f3eedae0.png)

Fijate que estas teniendo un problema de CORS porque cuando quiero realizar un registro me sucede lo mismo.

**Comment by ayrton08** [comment]
@FerDR89 le agregue la option en el header del fetch, avisame si te hace lo mismo, por que a mi no me tira ese error y lo probe de varios lugares
