### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by EzequielVilla** [ayrton08/dwf-m8-desafio-#2]
Buenas! Voy dejando algunas cosillas que vi !

Me gustaron mucho las capas de UI (no tiene state) y custom hooks, ademas de que tenes muchisimas cosas tipadas (tener los custom hooks muy tipados sirve bastante para escalar o para el equipo de trabajo ) 

- Estaria bueno centralizar todos los llamados a la API en un modulo solo dentro de la lib. No esta mal asi, pero en cuestion de orden las llamadas estan tanto en la lib como en hooks y se puede hacer confuso si escala. A lo sumo pondria una carpeta api y ahi dividirlo por report/user/pet.
No esta mal toda la division que hiciste de archivo por archivo (creo que en principio yo lo habia pensado igual) pero lo mejor seria como dije antes dividirlo en entidades report/user/pet e index en caso de ser un mix como useModal, useLogin, useLocation.

- La idea que vas a ir mejorando con el tiempo es que la capa pages quede limpia y llame a uno o mas componentes para montar lo que tiene que mostrar. Creo que lo tenes asi en parte es por la inercia de como lo veniamos haciendo, pero de aca en adelante (y creo que se menciona en algun momento de este modulo) es que por ejemplo pages Login tenga algo como:

```js
    export function Login(){
        return <LoginForm>
    }
```

Y despues vuelques todo lo que hay actualmente en ese componente. Es medio complejo en un principio, si queres manda un mensaje en discord o al privado y lo hablamos. De todas formas asi como lo hiciste esta perfecto, porque primero hay que volcar todo en un lugar y despues ir subdividiendolo (cosa que por ejemplo yo no hice en el modulo10 y termine tardando mucho mas por querer encararlo ya optimizando todo). Al estar todo en ese lugar uno ya puede empezar a decidir que dividir y como, ver que se repite y que no, asi que de todas formas esta perfecto.

Todo lo que mencione son anotaciones sutiles que te van a ir sirviendo para mas adelante y para tu futuro trabajo como dev, para mi la pagina esta bien, tiene su estilo propio lo cual es muy valorable y esta funcional, (tiene un bug cuando clickeas para mostrar la pass, despues no la vuelve a ocultar). En fin, exitos en los siguientes modulos!.

**Comment by ayrton08** [comment]
@EzequielVilla muchas gracias por tu devolución querido!! Dale voy tener en cuenta tus consejos.. abrazo grande genio!
